apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lendtech-repayment-api.fullname" . }}
  labels:
    {{- include "lendtech-repayment-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lendtech-repayment-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lendtech-repayment-api.selectorLabels" . | nindent 8 }}
    spec:
      hostAliases: {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lendtech-repayment-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: logback-mount
        configMap:
          name: logback-{{ .Chart.Name }}-configmap
          defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #ENV VALUES
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-configmap        
          - secretRef:
              name: {{ .Chart.Name }}-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: logback-mount
            mountPath: {{ .Values.mounts.logback }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .Values.livenessProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .Values.readinessProbe) . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nodeSelector.enabled }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
